// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGquvKNszP1fiELH6ucOPoKiYQZcNwNmo',
    appId: '1:637158461690:web:72f8badbae2e9edfdbb943',
    messagingSenderId: '637158461690',
    projectId: 'auth-firebase-ce5c0',
    authDomain: 'auth-firebase-ce5c0.firebaseapp.com',
    storageBucket: 'auth-firebase-ce5c0.firebasestorage.app',
    measurementId: 'G-JQL7KVFY72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpzvY0QbuRsakN4vHJQXiDGFLkAZtbSno',
    appId: '1:637158461690:android:b87daa148a8c02f4dbb943',
    messagingSenderId: '637158461690',
    projectId: 'auth-firebase-ce5c0',
    storageBucket: 'auth-firebase-ce5c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD755A9B14EUkmrps855scEOaw4Fktpids',
    appId: '1:637158461690:ios:3551f24422080fa7dbb943',
    messagingSenderId: '637158461690',
    projectId: 'auth-firebase-ce5c0',
    storageBucket: 'auth-firebase-ce5c0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExpense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD755A9B14EUkmrps855scEOaw4Fktpids',
    appId: '1:637158461690:ios:3551f24422080fa7dbb943',
    messagingSenderId: '637158461690',
    projectId: 'auth-firebase-ce5c0',
    storageBucket: 'auth-firebase-ce5c0.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthExpense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGquvKNszP1fiELH6ucOPoKiYQZcNwNmo',
    appId: '1:637158461690:web:5722fbd796832588dbb943',
    messagingSenderId: '637158461690',
    projectId: 'auth-firebase-ce5c0',
    authDomain: 'auth-firebase-ce5c0.firebaseapp.com',
    storageBucket: 'auth-firebase-ce5c0.firebasestorage.app',
    measurementId: 'G-RVLSD0QV1F',
  );
}
